export enum ErrorType {
  EXPERIENCE_NOT_FOUND = "EXPERIENCE_NOT_FOUND",

  EDUCATION_NOT_FOUND = "EDUCATION_NOT_FOUND",

  SKILL_NOT_FOUND = "SKILL_NOT_FOUND",

  SKILL_LINK_NOT_FOUND = "LINK_NOT_FOUND",

  PERSISTENCE = "PERSISTENCE",
}
