version: "3"
services:
  postgres:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=resume_user
      - POSTGRES_PASSWORD=resume_password
      - POSTGRES_DB=resume
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - resume
  resume:
    build:
      context: ../../
      dockerfile: packages/backend/backend.Dockerfile
    restart: always
    ports:
      - "9000:9000"
    expose:
      - 9000
    command: ["npm", "run", "start"]
    networks:
      - resume

      

volumes:
  postgres-data:
networks:
  resume:
    driver: bridge