version: "3"
services:
  postgres:
    image: postgres:17.4
    container_name: resume-postgres
    environment:
      - POSTGRES_USER=resume_user
      - POSTGRES_PASSWORD=resume_password
      - POSTGRES_DB=resume
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./infrastructure/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - resume
  resume:
    build:
      context: ../../
      dockerfile: packages/backend/backend.Dockerfile
    restart: always
    environment:
      - POSTGRES_URL=postgres://resume_user:resume_password@resume-postgres:5432/resume
    ports:
      - "9000:9000"
    expose:
      - 9000
    command: ["npm", "run", "start"]
    depends_on:
      - postgres
    networks:
      - resume

networks:
  resume:
    driver: bridge